version: '2'
networks:
  default:
    external:
      name: cic

services:
  server1:
    image: cicimages/environments-ubuntu
    privileged: true
    command: /sbin/init

  server2:
    image: cicimages/environments-ubuntu
    privileged: true
    command: /sbin/init

  server3:
    image: cicimages/environments-ubuntu
    privileged: true
    command: /sbin/init

