resources:

- name: repo
  type: git
  source:
    uri: http://git-server/repo.git
    branch: master

jobs:
- name: run tests
  plan:
  - do:
    - aggregate:
      - get: repo
        trigger: true
    - task: pytest
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: cicimages/wrappers-pytest
        inputs:
          - name: repo
        run:
          path: /bin/bash
          args:
            - -e
            - -c
            - -x
            - -l
            - -i
            - |
              pytest
