resources:

- name: repo
  type: git
  source:
    uri: http://git-server/repo.git
    branch: master

jobs:
- name: my-first-job
  plan:
  - do:
    - aggregate:
      - get: repo
        trigger: true
    - task: pointless-echo
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
        inputs:
        - name: repo
        run:
          path: sh
          args:
          - -e
          - -c
          - -x
          - |
            echo "Something worked"
