version: '3'
networks:
  default:
    external:
      name: cic

services:
  web1:
    hostname: web1
    privileged: true
    image: cicimages/environments-ubuntu
    ports: ["8080:80"]
    command: /sbin/init